### ISSUE TITLE
Can't access emoji picker for status change

### ISSUE THREAD

**Issue by jvrring** [SatanaDesigns/soon#2]
Hi there, 
Apologies if I can't seem to find it but it seems like I can't change the emoji for my status. Here's a screenshot of vanilla PTB and Soon PTB below.

![image](https://user-images.githubusercontent.com/67696935/208307846-45476084-420e-4d69-b8da-a74cf946e314.png)
![image](https://user-images.githubusercontent.com/67696935/208307856-2fdeee39-f0ae-4959-9519-c8155691e1ba.png)

**Comment by SatanaDesigns** [comment]
Hi! Sorry for the late response, been busy. We will be fixing this soon, thanks for bringing it to our attention :)

**Comment by SatanaDesigns** [comment]
Should be fixed, now.
